### ISSUE TITLE
Header NavLinks Opens on New Tabs

### ISSUE THREAD

**Issue by Ojochogwu866** [DevRel-Community-Africa/devrelcomafrica.xyz#22]
Header navigation links are opening in a new tab when clicked on, I think this would result to unnecessary clustering of tabs, as users would always expect header navlinks to open same tab.

**Comment by iamkalio** [comment]
Yeah I noticed the same issue while going through the site @hacktivist123  @0xJamin 
I fixed this issue with a PR

**Comment by codejagaban** [comment]
Thanks for the contribution
